# Generated by Django 3.2.3 on 2021-05-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WayPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityChineseName', models.CharField(max_length=256, verbose_name='城市中文名')),
                ('cityEnglishName', models.CharField(max_length=256, verbose_name='城市英文名')),
                ('airportChineseName', models.CharField(max_length=256, verbose_name='机场中文名')),
                ('airportEnglishName', models.CharField(max_length=256, verbose_name='机场英文名')),
                ('airportCode', models.CharField(max_length=256, verbose_name='机场三字码')),
                ('countryCode', models.CharField(max_length=256, verbose_name='国家二字码')),
                ('icao', models.CharField(max_length=256, verbose_name='国际四字码')),
                ('iata', models.CharField(max_length=256, verbose_name='三字码')),
                ('status', models.CharField(max_length=256, verbose_name='机场状态')),
                ('startTime', models.CharField(max_length=256, verbose_name='开始运营时间')),
                ('flightLevel', models.CharField(max_length=256, verbose_name='机场等级')),
                ('latitude', models.CharField(max_length=256, verbose_name='纬度')),
                ('longitude', models.CharField(max_length=256, verbose_name='经度')),
                ('timeZone', models.CharField(max_length=6, verbose_name='时区')),
            ],
            options={
                'verbose_name': '航点',
                'verbose_name_plural': '航点',
            },
        ),
    ]
